name: 'trainingflow_dbt'
version: '1.0.0'
config-version: 2

profile: 'trainingflow_databricks'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  trainingflow_dbt:
    bronze:
      +materialized: table
      +schema: trainingflow_bronze
    silver:
      +materialized: table
      +schema: trainingflow_silver
    gold:
      +materialized: table
      +schema: trainingflow_gold
